### 1. Write a function to compute 5/0 and use try/except to catch the exceptions

In [2]:
import numpy as np

In [4]:
def divide(a, b):
    try:
        c = a/b
    except ZeroDivisionError as ze:
        print(f'Number cannot be divided by zero, Error name: {ze}')
        c = np.NaN
    finally:
        return c

In [6]:
divide(5, 0)

Number cannot be divided by zero, Error name: division by zero


nan

### 2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.


In [7]:
subject = ["Americans", "Indians"]
verb = ["play", "watch"]
objects = ["Baseball", "Cricket"]

for sub in subject:
    for ver in verb:
        for obj in objects:
            print(sub, ver, obj)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### 3. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [48]:
X = [1,2,3,5]
N = 3
bool_val = True
def my_vander_matrix(X=None, N=None, bool_val=False):
    matrix = np.empty((len(X), 3), dtype=int) 
    for i in range(len(X)):
        for j in range(N):
            if bool_val:
                matrix[i][j] = X[i]**j
            else:
                matrix[i][j] = X[i]**(N-(j+1))
    return matrix

In [49]:
m = my_vander_matrix(X, N)

m

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [50]:
m = my_vander_matrix(X, N, bool_val=True)

m

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [52]:
np.vander(X, N, True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [53]:
np.vander(X, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])